### PR TITLE
Typo fix for NUCLEUS_HOST in webpack.config.js

### PR DESCRIPTION
**Pull request by elboletaire**

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Hey @elboletaire 

Thanks for the fix, before merging though can you sign the CLA mentioned in the README.

https://github.com/atlassian/nucleus#contributors

**Comment by elboletaire** [comment]
Done :+1:

**Comment by elboletaire** [comment]
BTW, I don't know if open an issue for this, or just start a new project from scratch, because that may be easier than getting this project up and running. 

I've a lot of problems trying to run this project locally. If I try to clone the source, everything crashes when trying to run `npm install` because there are TypeScript issues (and apparerntly `tslint` is executed during `npm install`, so packages can't get fully installed).

If I use the production version, I cannot imagine how to run the migrations (shouldn't run they automatically on first run?). With MySQL it complains about tables not being created. If I remove the database, it just complains about the missing table.

If using sqlite simply fails saying 'Failed to connect to DB', even trying with `:memory:` as storage.

So... does this project really work? If so, how could I get it up and running? 😞

**Comment by MarshallOfSound** [comment]
@elboletaire This projects uses a `yarn.lock` file to lock down its dependency tree.  In order to acquire the same dependency versions that we use (and avoid tslint / tsc changes breaking compilation) you should use `yarn` to install the `node_modules` as described in the [Setup](https://github.com/atlassian/nucleus#setup) section of the README.

I just fresh cloned this repository on a new machine and followed those setup commands and everything worked first try.  I'd recommend deleting your `node_modules` directory and then use `yarn` to install everything again.

> If I use the production version, I cannot imagine how to run the migrations

The migration functions are only run when they need to be, the function itself will check if it needs to be run.  E.g. [this one will return-fast](https://github.com/atlassian/nucleus/blob/master/src/db/sequelize/models/index.ts#L200)

>  With MySQL it complains about tables not being created.

The table structure should be created [here](https://github.com/atlassian/nucleus/blob/93cf73dc3fae05c550a6d78b2d2d75cc5fa204ec/src/db/sequelize/SequelizeDriver.ts#L33), if it isn't being made after resetting your `node_modules` as described above raise an issue with your logs and I can take a look.

**Comment by MarshallOfSound** [comment]
@elboletaire Appologies, it actually looks like there was an issue with first-run if the database schema hadn't been synced before.  It should be fixed on latest master, can you `git pull` and try again.  (You'll still have to use `yarn` to fix any tslint / tsc errors) 😄

**Comment by elboletaire** [comment]
Yeah for sure I can try, but I used `npm install` after multiple problems using yarn too (I use yarn as my default npm package manager).

**Comment by MarshallOfSound** [comment]
@elboletaire If running `yarn` on latest master is resulting in errors on your machine can you raise an issue with them and I'll take a look 👍

**Pull request closed without merging**
